[package]
name = "record-trace"
description = "Record a machine-level trace using the one-collect."
version = "0.0.0-dev"
edition = "2021"
license = "MIT"
repository = "https://github.com/microsoft/one-collect"

[dependencies]
ctrlc = "3.2"
engine = { path = "engine" }
